# Generated by Django 5.1.6 on 2025-02-17 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_donor_donor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_bloodtype',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_city',
            field=models.CharField(default='Thane', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid phone number.')]),
        ),
    ]
